<?php
// Variables
return [
  "creatorName" => env('RKAP_COMPANY_NAME', 'PT. Kereta Cepat Indonesia China'),
  "creatorUrl" => env('RKAP_COMPANY_URL', 'https://kcic.co.id'),
  "templateName" => env('RKAP_APP_SHORT_TITLE', 'RKAP'),
  "templateSuffix" => env('RKAP_COMPANY_TAGLINE', 'Sistem Rencana Kerja & Anggaran Perusahaan'),
  "templateVersion" => "1.0.0",
  "templateFree" => false,
  "templateDescription" => env('RKAP_COMPANY_TAGLINE', 'Sistem Rencana Kerja & Anggaran Perusahaan'),
  "templateKeyword" => "rkap, budgeting, budget planning, sistem rencana kerja dan anggaran perusahaan",
  "licenseUrl" => "",
  "livePreview" => "",
  "productPage" => "",
  "support" => "",
  "adminTemplates" => "",
  "bootstrapDashboard" => "",
  "ogTitle" => (env('RKAP_APP_SHORT_TITLE', 'RKAP')) . " - " . (env('RKAP_COMPANY_TAGLINE', 'Sistem Rencana Kerja & Anggaran Perusahaan')) . " :: " . (env('RKAP_COMPANY_NAME', 'Company')),
  "ogImage" => env('RKAP_LOGO_SIDEBAR', 'assets/img/brand/logo_sidebar.png'),
  "ogType" => "website",
  "documentation" => "",
  "repository" => "",
  "gitRepo" => "",
  "gitRepoAccess" => "",
  "githubFreeUrl" => "",
  "facebookUrl" => "",
  "twitterUrl" => "",
  "githubUrl" => "",
  "dribbbleUrl" => "",
  "instagramUrl" => ""
];
